### ISSUE TITLE
Ability to specify restart type

### ISSUE THREAD

**Issue by philk** [cloudkick/cast#16]
There are many services that can do a graceful reload of their configuration (apache2) or of an entirely new binary (nginx) through the use of different signals. Being able to specify that cast uses a specific signal during an upgrade would be a nice feature.

Something like this:
cast instances upgrade --graceful servicename0 servicename@v0.0.1-r2

With maybe a {"restart_signal":"HUP"} in the cast.json so cast knows what that process responds to.

**Comment by russellhaering** [comment]
Agreed, I'll work on this.

**Comment by russellhaering** [comment]
We've bumped this back beyond 0.2.0, we have some major service related work planned for the next release so it should make it in there.

**Comment by pquerna** [comment]
Archiving `cloudkick/cast`
