### ISSUE TITLE
Permissions wrong after install

### ISSUE THREAD

**Issue by philk** [cloudkick/cast#17]
Three files have incorrect permissions after the standard install that cause a normal user on the system not to be able to run cast.

The errors are:
Error: EBADF, Bad file descriptor '/opt/cast/cast/lib/extern/stacktrace.js'
Error: EBADF, Bad file descriptor '/opt/cast/cast/lib/extern/jspack/jspack.js'
Error: EBADF, Bad file descriptor '/opt/cast/cast/lib/util/version.js'

chmod a+rx filename
fixes the error and allows cast to run as a normal user.

**Comment by Kami** [comment]
Thanks for the report, I have fixed it. The fix will be included in the next version.

To make sure something like this doesn't happen anymore, we need to modify the install tests to also verify the file permissions and make sure it works properly when installing cast as a normal user.
