### ISSUE TITLE
Should return non-zero exit on error

### ISSUE THREAD

**Issue by philk** [cloudkick/cast#18]
Trying to integrate cast with buildbot and it seems like most failure circumstances return zero as their exit code...causing buildbot to think the steps ran successfully when they didn't.

Error: Failed to find a manifest file cast.json in /data/buildslave/projectname-cast/build
Error: Bundle projectname version projectname@v0.0.1-r4 doesn't exist
Error: Missing required arguments: version

Probably more I haven't run into. I think any error should exit non-zero.

**Comment by russellhaering** [comment]
While we're at it we should handle client errors in a central location. Probably we should pass a callback to the command handlers.

**Comment by Kami** [comment]
Resolved and merged into develop - da356646f48201679c4573d90dddd45b93dec0c6.
