### ISSUE TITLE
Create a serialization framework which can be used with our classes which are exposed through the API

### ISSUE THREAD

**Issue by Kami** [cloudkick/cast#2]
Currently we expose most of our classes (Instance, Service, Bundle, etc..) through our API in a JSON format in some way or another.

The problem is that we always end up creating the actual response object which we than `JSON.stringify` and expose through the API in each service HTTP endpoint module separately. This means we have a lot unnecessary and repeated code there.

I think we should create a new class called `Serializable` from which all of our objects which are exposed through the API should inherit from.

This class should have a method named `serialize(type='json', [attributes])`.

This method should return a string which is a serialized version of this object.

The optional `attributes` parameter is an array and specifies which class attributes we want to serialize (defaults to 'all').

Attributes can also be callables, because in many cases we need to call some class method to get a value which we need.

attributes array could for example look like this: `[ 'name', 'is_enabled()', 'status' ]` (note: `is_enabled` is a callable / class method).

Ideally the method would be sync, but the problem is that most of the class methods which needs to be called to obtain some values are async so the actual method signature will in the end probably look something like this: `serialize(type='json', [attributes='all'], callback)`

**Comment by wirehead** [comment]
everything but the attributes part (which is short) is done on the ELE side with swiz.js

**Comment by Kami** [comment]
Great.

Would be nice to decouple it from ELE and upload it as a separate project.

Than I can also add attributes part if you don't have time :)

**Comment by pquerna** [comment]
We should extract swiz/valve into a separate node/npm module and re-use them.

**Comment by Kami** [comment]
That's completed.
