### ISSUE TITLE
Did the project stop?

### ISSUE THREAD

**Issue by abh** [cloudkick/cast#35]
Does Cloudkick still use Cast or did the project stop?  All activity seems like it stopped at the same time about 5 months ago. :-/

**Comment by russellhaering** [comment]
@Kami and I are spending most of our time on another project right now. We developed and now largely use [Dreadnot](https://github.com/racker/dreadnot) internally for deployment, though the focus is somewhat different (Dreadnot focuses on central orchestration of deployment, while Cast was entirely dedicated to what happened server-side). We've talked about integrating them, but its not on the roadmap right now.

**Comment by abh** [comment]
We're evaluating various deployment systems to replace our current system and Dreadnot actually looks more along the lines of what we are looking for than Cast did, so that's great!  :-)

You should update the Cast wiki with a reference to Dreadnot.
